site_name: Akshay Malige
site_url: https://akshaymalige.github.io/

theme:
  name: material
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: sunrise
      primary: custom
      accent: custom
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: midnight
      primary: custom
      accent: custom
      toggle:
        icon: material/white-balance-sunny
        name: Switch to light mode
  features:
    - navigation.instant
    - navigation.footer
    - navigation.tabs
    - navigation.tracking
    - navigation.sections
    - navigation.indexes
    - navigation.top
    - navigation.expand
    - toc.integrate
    - toc.follow

nav:
  - Home: index.md
  - Projects: projects.md
  - Publications: publications.md
  - Blog: blog.md
  - CV: cv.md

markdown_extensions:
  - admonition
  - attr_list
  - md_in_html
  - footnotes
  - tables
  - toc:
      permalink: true

extra_css:
  - stylesheets/extra.css
